Repository PDG-2023/Project, pull requests merged in 2023-05, with the labels that each got.

#40 Api Implementation
  apps/backend/src/main/java/ch/heig/pdg/backend/BackendApplication.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/AbstractDataMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/CategoryMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/InventoryMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/ItemMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/ItemModelMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/LocationMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/MovementMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/UserMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/AbstractEntity.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/Location.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/AbstractController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/CategoryController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/InventoryController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/ItemController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/ItemModelController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/LocationController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/MovementController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/UserController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/AbstractService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/CategoryService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/InventoryService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/ItemModelService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/ItemService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/LocationService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/MovementService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/UserService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/utils/DateFormatUtil.java
  apps/backend/src/main/resources/api.yaml
  apps/backend/src/main/resources/data.sql
Labels: 49.3

#42 Dev/checkstyle
  .github/workflows/test.yml
  apps/backend/checkstyle.xml
  apps/backend/pom.xml
  apps/backend/src/main/java/ch/heig/pdg/backend/BackendApplication.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/AbstractDataMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/CategoryMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/IDataTransferObjectManager.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/InventoryMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/ItemMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/LocationMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/MovementMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/AbstractEntity.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/Category.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/Item.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/Location.java
  apps/backend/src/main/java/ch/heig/pdg/backend/exception/exceptions/ForbiddenOperationException.java
  apps/backend/src/main/java/ch/heig/pdg/backend/exception/exceptions/InternalServerErrorException.java
  apps/backend/src/main/java/ch/heig/pdg/backend/exception/exceptions/NotFoundException.java
  apps/backend/src/main/java/ch/heig/pdg/backend/exception/exceptions/PaginationException.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/AbstractController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/AuthenticationController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/CategoryController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/InventoryController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/ItemController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/ItemModelController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/LocationController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/MovementController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/presentation/UserController.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/CategoryRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/CriteriaRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/InventoryRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/ItemModelRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/ItemRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/LocationRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/MovementRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/UserRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/criteria/CriteriaRepository.java
  apps/backend/src/main/java/ch/heig/pdg/backend/repositories/criteria/CriteriaRepositoryImpl.java
  apps/backend/src/main/java/ch/heig/pdg/backend/security/filters/AuthorizationFilter.java
  apps/backend/src/main/java/ch/heig/pdg/backend/security/services/JWTValidatorService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/security/utils/InvalidJWTException.java
  apps/backend/src/main/java/ch/heig/pdg/backend/services/AbstractService.java
  apps/backend/src/main/java/ch/heig/pdg/backend/utils/DateFormatUtil.java
  apps/backend/src/main/java/ch/heig/pdg/backend/utils/HugoSearchFilter.java
  apps/backend/src/main/resources/application.properties
Labels: (╯°□°)╯︵ ┻━┻

#50 Remove Location from Item
  apps/backend/src/main/java/ch/heig/pdg/backend/dto/mapping/ItemMapper.java
  apps/backend/src/main/java/ch/heig/pdg/backend/entities/Item.java
Labels: table-ronde-syndicats

#51 [BUGFIX] format yaml and use "
  apps/backend/src/main/resources/api.yaml
Labels: 49.3
